name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT_ID: gcp-project-id
  GCR_REGISTRY: gcr.io/DevOps-task
  HELM_CHART_REPO: https://helm-chart-repo.com

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_SECRET }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and Push Docker Images
        run: |
          for dir in ./microservices/*; do
            service_name=$(basename "$dir")
            docker build -t "${{ env.GCR_REGISTRY }}/$service_name:$GITHUB_SHA" "$dir"
            docker push "${{ env.GCR_REGISTRY }}/$service_name:$GITHUB_SHA"
          done

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Deploy Services to Kubernetes
        run: |
          for dir in ./microservices/*; do
            service_name=$(basename "$dir")
            helm upgrade --install "$service_name" "${{ env.HELM_CHART_REPO }}/$service_name" --namespace default --set image.repository="${{ env.GCR_REGISTRY }}/$service_name",image.tag="$GITHUB_SHA"
          done
          
